name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace API Key
        run: |
          sed -i "s/%%GOOGLE_PLACES_API_KEY%%/${{ secrets.GOOGLE_PLACES_API_KEY }}/g" utils/locationUtils.js
          echo "API key replacement completed"
          
      - name: Verify API Key Replacement
        run: |
          if grep -q "%%GOOGLE_PLACES_API_KEY%%" utils/locationUtils.js; then
            echo "ERROR: API key placeholder still exists!"
            exit 1
          else
            echo "SUCCESS: API key has been replaced"
          fi
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRIBE_RESTAURANT_ROULETTE }}'
          channelId: live
          projectId: tribe-restaurant-roulette